### ISSUE TITLE
Offer an Ubuntu/Debian PPA for Updates

### ISSUE THREAD

**Issue by xd1936** [dh4/mupen64plus-qt#28]
Ubuntu has an older version (1.8) of mupen64plus-qt in [it's Launchpad repository](https://launchpad.net/ubuntu/xenial/+package/mupen64plus-qt). Please offer us a way to stay up-to-date, other than manually downloading and installing the binary ourselves. If this isn't possible, offering a .deb package of this program would be an alternative.

**Comment by dh4** [comment]
Unfortunately the maintainer of the Debian/Ubuntu package hasn't responded in 6 months or so. The package has not been updated to 1.10 yet within the Debian repositories:
https://tracker.debian.org/pkg/mupen64plus-qt

I don't have any intention of setting up a PPA as I don't use a Debian-based system, though you are welcome to do so.

I have scripts written to build a .deb file here (there's instructions in the README):
https://github.com/dh4/mupen64plus-qt/tree/master/dist/debian

I did not automate this with Travis originally since the LTS Ubuntu required a different version of libquazip to be built with this vs. the latest Ubuntu, meaning multiple .deb packages would need to be created for the different versions. I'll look into if it's sane to start offering a .deb package going forward.

**Comment by dh4** [comment]
This is up to date in the Debian repositories now, so I'm going to close this issue.

https://tracker.debian.org/pkg/mupen64plus-qt
