### ISSUE TITLE
Setting the default path for mupen64plus.cfg

### ISSUE THREAD

**Issue by sergiobenrocha2** [dh4/mupen64plus-qt#7]
Hi, I'm trying to set by default mupen config on linux, but it seems the program doesn't recognize the "~/", if I use the full path (/home/user/.config...) it works.

The patch:

```
Index: mupen64plus-qt/src/mainwindow.cpp
===================================================================
--- mupen64plus-qt.orig/src/mainwindow.cpp	2015-05-23 03:22:19.918273094 -0300
+++ mupen64plus-qt/src/mainwindow.cpp	2015-05-23 03:23:00.874857458 -0300
@@ -355,7 +355,7 @@
     if (mupen64Path == "" && dataPath == "" && pluginPath == "") {
 #ifdef Q_OS_LINUX
         //If user has not entered any settings, check common locations for them
-        QStringList mupen64Check, dataCheck, pluginCheck;
+        QStringList mupen64Check, dataCheck, pluginCheck, configCheck;
 
         mupen64Check << "/usr/games/mupen64plus"
                      << "/usr/bin/mupen64plus";
@@ -368,6 +368,8 @@
         dataCheck    << "/usr/share/mupen64plus"
                      << "/usr/share/games/mupen64plus";
 
+        configCheck  << "~/.config/mupen64plus";
+
 
         foreach (QString check, mupen64Check)
             if (QFileInfo(check).exists())
@@ -380,6 +382,11 @@
         foreach (QString check, dataCheck)
             if (QFileInfo(check+"/mupen64plus.ini").exists())
                 SETTINGS.setValue("Paths/data", check);
+
+        foreach (QString check, configCheck)
+            if (QFileInfo(check+"/mupen64plus.cfg").exists())
+                SETTINGS.setValue("Paths/config", check);
+
 #endif
 
 #ifdef Q_OS_WIN

```

**Comment by dh4** [comment]
Thanks for the patch. I initially left this out since there was no point in setting --configdir unless the user wanted to specify a non-standard directory, but since the editor I've included with this launcher now uses that setting to find mupen64plus.cfg, it's a good idea to check for it.

Still not perfect since the file won't be there until a user has run Mupen64Plus at least once, but it's better than nothing.

And yes, Qt won't recognize ~ since that's a bash convention. You can see the Qt way grabbing a user's home directory in the commit.

**Comment by sergiobenrocha2** [comment]
sweet :)

**Comment by sergiobenrocha2** [comment]
It could try launch mupen in the first time you open it. Even without rom, it'll create the config file.

**Comment by dh4** [comment]
I considered that but it felt a little hack-ish to me. What I've done instead is move the config autoload to it's own if statement. This means it will always check even after it's found the executable unless the user has already specified another directory.
